---
title: "Delay vignette"
author: "darthaline"
date: "01 Dec 2020"
output:
  html_notebook:
    toc: true
---

# About

Error arises when attempting to run the code from the [DDE vignette](https://cran.csiro.au/web/packages/diffeqr/vignettes/dde.html).

Small modification: I substituted `tspan` in ```JuliaCall::julia_assign("constant_lags", tspan)``` for `constant_lags`, but that doesn't resolve the error problem.

```{r}
Sys.setenv(LANG = "en")

#diffeqr setup
library(diffeqr)
library(JuliaCall)
dyn.load("C:/Users/alinaa/AppData/Local/Julia 1.5.0/bin/libdSFMT.dll")
julia_setup(JULIA_HOME="C:/Users/alinaa/AppData/Local/Julia 1.5.0/bin")
de <- diffeqr::diffeq_setup()
dyn.load("C:/Users/alinaa/AppData/Local/Julia 1.5.0/bin/libopenlibm.DLL")

#calculation
f <- JuliaCall::julia_eval("function f(du, u, h, p, t)
  du[1] = 1.1/(1 + sqrt(10)*(h(p, t-20)[1])^(5/4)) - 10*u[1]/(1 + 40*u[2])
  du[2] = 100*u[1]/(1 + 40*u[2]) - 2.43*u[2]
end")
h <- JuliaCall::julia_eval("function h(p, t)
  [1.05767027/3, 1.030713491/3]
end")
u0 <- c(1.05767027/3, 1.030713491/3)
tspan <- c(0.0, 100.0)
constant_lags <- c(20.0)
JuliaCall::julia_assign("u0", u0)
JuliaCall::julia_assign("tspan", tspan)
JuliaCall::julia_assign("constant_lags", constant_lags)
prob <- JuliaCall::julia_eval("DDEProblem(f, u0, h, tspan, constant_lags = constant_lags)")
sol <- de$solve(prob,de$MethodOfSteps(de$Tsit5()))
udf <- as.data.frame(t(sapply(sol$u,identity)))
```

# Session info

```{r sessionInfo}
sessionInfo()
```